export const timeline = {
  id: 't3',
  title: 'La Ville',
  order: [
    't3.premier-jour',
    't3.dossier-anciennete',
    't3.la-pause',
    't3.dossier-urgence',
    't3.reunion-service',
    't3.la-regle',
    't3.la-fenetre',
    't3.le-cafe',
    't3.premiere-application',
    't3.la-routine',
    't3.consequence-differee',
    't3.le-rapport',
    't3.nadia',
    't3.nadia-dossier',
    't3.exception',
    't3.precedent',
    't3.farid-le-sait',
    't3.la-pression',
    't3.fausse-accalmie',
    't3.la-greve',
    't3.retour-connu',
    't3.retour-inconnu',
    't3.la-liste',
    't3.apres-la-liste',
    't3.quatre-cent-dix-sept',
    't3.ce-qui-reste',
    't3.le-registre',
    't3.sortie',
  ],
} as const;
