export const timeline = {
  id: 't0',
  title: 'L’Examen',
  order: [
    't0.prologue',
    't0.bonsoir',
    't0.l-innocent',
    't0.ce-qui-est-note',
    't0.le-pardon',
    't0.la-copie',
    't0.le-dernier-appel',
    't0.quelques-questions',
    't0.le-bonheur',
    't0.un-defaut',
    't0.le-temoin',
    't0.la-promesse',
    't0.le-traitre',
    't0.la-pause',
    't0.ton-autre-vie',
    't0.l-analyse',
    't0.le-sacrifice-invisible',
    't0.le-bouton-inutile',
    't0.la-seconde-chance',
    't0.la-douleur',
    't0.le-trajet',
    't0.les-vingt-annees',
    't0.la-contradiction',
    't0.l-exception',
    't0.le-mensonge',
    't0.ta-loi',
    't0.la-porte',
    't0.epilogue',
  ],
} as const;
